export enum ORDER_STATUS {
  UNPAID = "UNPAID",
  READY_TO_SHIP = "READY_TO_SHIP",
  PROCESSED = "PROCESSED",
  RETRY_SHIP = "RETRY_SHIP",
  SHIPPED = "SHIPPED",
  TO_CONFIRM_RECEIVE = "TO_CONFIRM_RECEIVE",
  IN_CANCEL = "IN_CANCEL",
  CANCELLED = "CANCELLED",
  TO_RETURN = "TO_RETURN",
  COMPLETED = "COMPLETED",
  INVOICE_PENDING = "INVOICE_PENDING",
}

export enum RETURN_STATUS {
  REQUESTED = "REQUESTED",
  ACCEPTED = "ACCEPTED",
  CANCELLED = "CANCELLED",
  JUDGING = "JUDGING",
  REFUND_PAID = "REFUND_PAID",
  CLOSED = "CLOSED",
  PROCESSING = "PROCESSING",
  SELLER_DISPUTE = "SELLER_DISPUTE",
}

export enum LOGISTICS_STATUS {
  LOGISTICS_NOT_START = "LOGISTICS_NOT_START",
  LOGISTICS_REQUEST_CREATED = "LOGISTICS_REQUEST_CREATED",
  LOGISTICS_PICKUP_DONE = "LOGISTICS_PICKUP_DONE",
  LOGISTICS_PICKUP_RETRY = "LOGISTICS_PICKUP_RETRY",
  LOGISTICS_PICKUP_FAILED = "LOGISTICS_PICKUP_FAILED",
  LOGISTICS_DELIVERY_DONE = "LOGISTICS_DELIVERY_DONE",
  LOGISTICS_DELIVERY_FAILED = "LOGISTICS_DELIVERY_FAILED",
  LOGISTICS_REQUEST_CANCELED = "LOGISTICS_REQUEST_CANCELED",
  LOGISTICS_COD_REJECTED = "LOGISTICS_COD_REJECTED",
  LOGISTICS_READY = "LOGISTICS_COD_REJECTED",
  LOGISTICS_INVALID = "LOGISTICS_INVALID",
  LOGISTICS_LOST = "LOGISTICS_LOST",
  LOGISTICS_UNKNOWN = "LOGISTICS_UNKNOWN",
}

export enum CANCEL_REASON {
  OUT_OF_STOCK = "OUT_OF_STOCK",
  CUSTOMER_REQUEST = "CUSTOMER_REQUEST",
  UNDELIVERABLE_AREA = "UNDELIVERABLE_AREA",
  COD_NOT_SUPPORTED = "COD_NOT_SUPPORTED",
}

export enum OPERATION {
  ACCEPT = "ACCEPT",
  REJECT = "REJECT",
}

export enum SHIPPING_DOCUMENT_TYPE {
  NORMAL_AIR_WAYBILL = "NORMAL_AIR_WAYBILL",
  THERMAL_AIR_WAYBILL = "THERMAL_AIR_WAYBILL",
  NORMAL_JOB_AIR_WAYBILL = "NORMAL_JOB_AIR_WAYBILL",
  THERMAL_JOB_AIR_WAYBILL = "THERMAL_JOB_AIR_WAYBILL",
}

export enum ADDRESS_TYPE {
  DEFAULT_ADDRESS = "DEFAULT_ADDRESS",
  PICKUP_ADDRESS = "PICKUP_ADDRESS",
  RETURN_ADDRESS = "RETURN_ADDRESS",
}

export enum DISPUTE_REASON {
  NON_RECEIPT = "NON_RECEIPT",
  OTHER = "OTHER",
  NOT_RECEIVED = "NOT_RECEIVED",
  UNKNOWN = "UNKNOWN",
}

export enum MESSAGE_TYPE {
  text = "text",
  sticker = "sticker",
  image = "image",
  item = "item",
  order = "order",
}

export enum ITEM_STATUS {
  NORMAL = "NORMAL",
  DELETED = "DELETED",
  BANNED = "BANNED",
  UNLIST = "UNLIST",
}
